#!/usr/bin/env python3

helpstr = "'''\n"
with open('README.md') as f:
    helpstr += f.read()
helpstr += "'''\n"

with open(f'src/lib1305/__init__.py', 'w') as f:
    f.write(helpstr)
    f.write('\n')
    f.write(f'from .onetimeauth import poly1305\n')
